min_annotations: 30
max_taxons: 70
go_annotation_raw: /data/home/pitagoras/data/go/goa_uniprot_all.gaf.gz
esm_libraries: /storages/macaiba/pitagoras/vol/data/esm_embedding
esm_processes: 30
esm_models_to_use: [30, 33]
testing_perc: 0.25
validation_perc: 0.15
training_processes: 24
parsing_processes: 8
patience: 10
epochs: 40
deepfri_path: /data/home/pitagoras/software/deepfri_main
interpro_dir: /data/home/pitagoras/data/interpro